### ISSUE TITLE
Error in CSS file - Indent

### ISSUE THREAD

**Issue by Prugh** [ucsf-web-services/ucsf_webedit#13]
Looks like a copy/paste error in your webedit CSS – should be indent-1,2,3,4 

/\* indentation classes */
.webedit-indent-1:not(.webedit-alignright) {
                margin-left: 5em;
}
.webedit-indent-1:not(.webedit-alignright) {
                margin-left: 10em;
}
.webedit-indent-1:not(.webedit-alignright) {
                margin-left: 15em;
}
.webedit-indent-1:not(.webedit-alignright) {
                margin-left: 20em;
}

**Comment by stopfstedt** [comment]
thanks @Prugh , looking into it.

**Comment by stopfstedt** [comment]
here: https://github.com/ucsf-drupal/ucsf_webedit/blob/7.x-1.x/ucsf_webedit.css#L31

**Comment by erykmynn** [comment]
it looks fine here, but did you get a chance to test it?

**Comment by stopfstedt** [comment]
tested in vanilla starter kit site, this fix works.
